name: RPA To Zendesk Refund Interface
on:
 workflow_dispatch:
    inputs:
      subscriptionId:
        description: 'SubscriptionId'
        required: true
      resourceGroupName:
        description: 'Resource group name'
        required: true

permissions:
  id-token: write
  contents: read
    
jobs: 
  build-and-Deploy:
    runs-on: ubuntu-latest
    
    env:
     ENV_RESOURCEGROUP: RG-weu-apim-acc
     ENV_RESOURCEGROUPLOCATION: westeurope
    steps:
     
           # Checkout code
    - uses: actions/checkout@main
     
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION }}
  
    - name: 'Run Azure CLI commands'
      run: |
          az account show
          az group list
          pwd 
      



      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{secrets.AZURE_SUBSCRIPTION}}
        resourceGroupName: RG-weu-apim-acc
        template: ./SAPRefund_Apim_Bicep/zendesksaprefund.bicep
        parameters: ./SAPRefund_Apim_Bicep/Zendesksaprefund.parameters.qas.json
        failOnStdErr: false
        
        
  VerifyDeployment:
    name: Verify Deployment
    runs-on: ubuntu-latest
    environment: 'Test'
    needs: [build-and-Deploy]

    steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-node@v1
       with:
        node-version: '12.x'
     - name: Send Message from POST MAN and verify the interface 
       run: |
        
        echo "::send message to apim url https://apim-uat.bo.tomtom-global.com/rpa/zendeskrefund via portal"
        
  build-and-Deploy-prd:
     runs-on: ubuntu-latest
     needs: [build-and-Deploy,VerifyDeployment]

     env:
      ENV_RESOURCEGROUP: RG-weu-apim-prod
      ENV_RESOURCEGROUPLOCATION: westeurope
     steps:
     
           # Checkout code
     - uses: actions/checkout@main
     
     - name: 'Az CLI login'
       uses: azure/login@v1
       with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_PROD }}
  
     - name: 'Run Azure CLI commands'
       run: |
          az account show
          az group list
          pwd 
          
    

      # Deploy Bicep file
     - name: deploy Prd
       uses: azure/arm-deploy@v1
       with:
        subscriptionId: ${{secrets.AZURE_SUBSCRIPTION_PROD}}
        resourceGroupName: RG-weu-apim-prod
        template: ./SAPRefund_Apim_Bicep/zendesksaprefund.bicep
        parameters: ./SAPRefund_Apim_Bicep/Zendesksaprefund.parameters.prd.json
        failOnStdErr: false

    
        
  

